### PR TITLE
Revert "publish semantic-convention-utils"

### PR DESCRIPTION
**Pull request by pavan-traceable**
Reverts hypertrace/hypertrace-ingester#198

### CODE REVIEW

**Review by rish691 — APPROVED** [review]

**Review by skjindal93 — APPROVED** [review]

**Comment by skjindal93** [comment]
We can continue publishing the semantic convention utils, as we discussed, for the downstream consumers to use them

**Comment by aaron-steinfeld** [comment]
> We can continue publishing the semantic convention utils, as we discussed, for the downstream consumers to use them

What's the reasoning here? Our architectural plan is to remove all of these utils, so spreading them further is a major issue IMO.

**Comment by skjindal93** [comment]
> > We can continue publishing the semantic convention utils, as we discussed, for the downstream consumers to use them
> 
> What's the reasoning here? Our architectural plan is to remove all of these utils, so spreading them further is a major issue IMO.

Since we are getting rid of the first class fields, how would the consumers read the values from the attributes? I liked the common place of having `EnrichedSpanUtils` definitely, which is the current way of reading of values from the span

**Comment by aaron-steinfeld** [comment]
mentioned offline, but the attribute reader, not the span utils are meant to be the successor to the first class fields.

**Pull request closed without merging**
